/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface PlateButton {}
  interface PlateButtonAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'PlateButton': Components.PlateButton;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'plate-button': Components.PlateButtonAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPlateButtonElement extends Components.PlateButton, HTMLStencilElement {}
  var HTMLPlateButtonElement: {
    prototype: HTMLPlateButtonElement;
    new (): HTMLPlateButtonElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'plate-button': HTMLPlateButtonElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'plate-button': HTMLPlateButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
