/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PlateButton {}
  interface PlateButtonAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PlateButton': Components.PlateButton;
  }

  interface StencilIntrinsicElements {
    'plate-button': Components.PlateButtonAttributes;
  }


  interface HTMLPlateButtonElement extends Components.PlateButton, HTMLStencilElement {}
  var HTMLPlateButtonElement: {
    prototype: HTMLPlateButtonElement;
    new (): HTMLPlateButtonElement;
  };

  interface HTMLElementTagNameMap {
    'plate-button': HTMLPlateButtonElement
  }

  interface ElementTagNameMap {
    'plate-button': HTMLPlateButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
